# This is our first Github Actions workflow!

name: Lint Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10.7
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.7'

    - name: Install poetry
      uses: snok/install-poetry@v1
      with: 
        virtualenvs-in-project: true

    - name: Load cached venv
      uses: actions/cache@v4
      id: cached-poetry-dependencies
      with:
        path: .venv
        key: venv-${{ runner.os }}-${ hashFiles('**/poetry.lock') }}

      
    - name: Install dependencies using poetry
      run: poetry run make install

    - name: Lint with flake8
      run: poetry run make check

      